wandb_version: 1

L:
  desc: null
  value: 0.1
_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1659033224
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 19
      4: 3.10.4
      5: 0.12.21
      8:
      - 1
      - 5
b:
  desc: null
  value: 1024
epochs:
  desc: null
  value: 10000
